---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token

  context: |
    argocdUrl: https://argocd.ys7.me

  template.app-health-degraded: |
    slack:
      blocks: |
        [{
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": "{{.app.metadata.name}}"
          }
        },
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "text": ":red_circle: Application health has degraded",
            "emoji": true
          }
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "mrkdwn",
              "text": "Health Status: *{{.app.status.health.status}}*"
            },
            {
              "type": "mrkdwn",
              "text": "<{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|Open in ArgoCD>"
            }
          ]
        }]
  template.app-sync-failed: |
    slack:
      blocks: |
        [{
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": "{{.app.metadata.name}}"
          }
        },
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "text": ":red_circle: Application sync has failed",
            "emoji": true
          }
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "mrkdwn",
              "text": "Sync Status: *{{.app.status.sync.status}}*"
            },
            {
              "type": "mrkdwn",
              "text": "<{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|Open in ArgoCD>"
            }
          ]
        }]
  template.app-sync-status-unknown: |
    slack:
      blocks: |
        [{
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": "{{.app.metadata.name}}"
          }
        },
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "text": ":red_circle: Application sync status is 'Unknown'",
            "emoji": true
          }
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "mrkdwn",
              "text": "<{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|Open in ArgoCD>"
            }
          ]
        }]

  trigger.on-health-degraded: |
    - description: Application has degraded
      send: [app-health-degraded]
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send: [app-sync-failed]
      when: app.status.operationState != nil and app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send: [app-sync-status-unknown]
      when: app.status.sync.status == 'Unknown'

  subscriptions: |
    - recipients:
        - slack:self-notifications
      triggers:
        - on-health-degraded
        - on-sync-failed
        - on-health-degraded
