apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-application-controller
          resources:
            requests:
              cpu: 2.0
              memory: 2Gi
            limits:
              cpu: 2.0
              memory: 2Gi
