---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  annotations:
    "iam.gke.io/gcp-service-account": "argocd@dev-infra.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  annotations:
    "iam.gke.io/gcp-service-account": "argocd@dev-infra.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
  annotations:
    iam.gke.io/gcp-service-account: argocd@dev-infra.iam.gserviceaccount.com
