---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  annotations:
    avp.kubernetes.io/path: projects/dev-infra/secrets/argocd-cm
data:
  url: https://argocd.ys7.me
  statusbadge.enabled: "true"
  users.anonymous.enabled: "false"
  admin.enabled: "false"
  application.resourceTrackingMethod: annotation

  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: <argocd-cm | jsonPath {.clientID}>
        clientSecret: <argocd-cm | jsonPath {.clientSecret}>
      type: oidc
      id: google
      name: Google

  # Ignore resources secrtion due to automatic adjustments in GKE Autopilot
  resource.customizations.ignoreDifferences.all: |
    jqPathExpressions:
      - .spec.template.spec.initContainers[].resources
      - .spec.template.spec.containers[].resources

  # Don't auto-format the line below. It looks really weird otherwise :)
  # prettier-ignore
  resource.customizations.ignoreDifferences.cilium.io_CiliumClusterwideNetworkPolicy: |
    jsonPointers:
      - "/status"

  resource.customizations: |
    "*.gcp.upbound.io/*":
      health.lua: |
        hs = {
          status = "Progressing",
          message = "Provisioning ..."
        }


        if obj.status == nil or obj.status.conditions == nil then
          return hs
        end

        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "LastAsyncOperation" then
            if condition.status == "False" then
              hs.status = "Degraded"
              hs.message = condition.message
              return hs
            end
          end

          if condition.type == "Synced" then
            if condition.status == "False" then
              hs.status = "Degraded"
              hs.message = condition.message
              return hs
            end
          end

          if condition.type == "Ready" then
            if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = "Resource is up-to-date."
              return hs
            end
          end
        end

        return hs
