apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      automountServiceAccountToken: true
      initContainers:
        - name: toolchain-setup
          image: busybox:1.36
          env:
            - name: CUE_VERSION
              value: 0.8.2
            - name: AVP_VERSION
              value: 1.17.0
            - name: GCR_VERSION
              value: 2.1.22
          command:
            - sh
            - -c
            - |
              wget https://github.com/cue-lang/cue/releases/download/v$(CUE_VERSION)/cue_v$(CUE_VERSION)_linux_amd64.tar.gz -O - | tar -xz && 
              chmod +x cue && mv cue /tools/cue

              wget https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -O argocd-vault-plugin &&
              chmod +x argocd-vault-plugin && mv argocd-vault-plugin /tools/argocd-vault-plugin

              wget https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v$(GCR_VERSION)/docker-credential-gcr_linux_amd64-$(GCR_VERSION).tar.gz -O - | tar -xz &&
              chmod +x docker-credential-gcr && mv docker-credential-gcr /var/run/docker-credential-gcr/docker-credential-gcr
              PATH=/var/run/docker-credential-gcr/:$PATH HOME=/var/run/config docker-credential-gcr configure-docker --include-artifact-registry
              chmod +r /var/run/config/.docker/config.json
          volumeMounts:
            - mountPath: /tools
              name: tools
            - mountPath: /var/run/docker-credential-gcr
              name: docker-credential-gcr
            - mountPath: /var/run/config/.docker
              name: docker-config
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/docker-credential-gcr
              name: docker-credential-gcr
              subPath: docker-credential-gcr
              readOnly: true
            - mountPath: /home/argocd/.docker
              name: docker-config
              readOnly: true
        - name: cue-plugin
          command: [/var/run/argocd/argocd-cmp-server]
          image: busybox:1.36
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: cue-plugin
            - mountPath: /usr/local/bin/cue
              subPath: cue
              name: tools
            - mountPath: /tmp
              name: cmp-tmp
          resources:
            requests:
              cpu: 4
              memory: 4Gi
            limits:
              cpu: 4
              memory: 4Gi
        - name: argocd-vault-plugin
          command: [/var/run/argocd/argocd-cmp-server]
          env:
            - name: AVP_TYPE
              value: gcpsecretmanager
          image: quay.io/argoproj/argocd:v2.11.0
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: argocd-vault-plugin
            - mountPath: /usr/local/bin/argocd-vault-plugin
              subPath: argocd-vault-plugin
              name: tools
            - mountPath: /tmp
              name: cmp-tmp
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 500m
              memory: 2Gi
      volumes:
        - configMap:
            name: cue-plugin
          name: cue-plugin
        - configMap:
            name: argocd-vault-plugin
          name: argocd-vault-plugin
        - emptyDir: {}
          name: cmp-tmp
        - emptyDir: {}
          name: tools
        - emptyDir: {}
          name: docker-credential-gcr
        - emptyDir: {}
          name: docker-config
