apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  annotations:
    avp.kubernetes.io/path: projects/dev-infra/secrets/argocd-secret
type: Opaque
stringData:
  server.secretkey: <argocd-secret | jsonPath {.server-secretkey}>
  webhook.github.secret: <argocd-secret | jsonPath {.webhook-github-secret}>
