apiVersion: v1
kind: Secret
metadata:
  name: repo-iac
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/selfuryon/kubernetes-cue-example
  name: iac
