apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  annotations:
    avp.kubernetes.io/path: projects/dev-infra/secrets/argocd-github-creds
stringData:
  type: git
  url: https://github.com/selfuryon
  githubAppID: "361263"
  githubAppInstallationID: "39670193"
  githubAppPrivateKey: <argocd-github-creds>
