apiVersion: v1
kind: Secret
metadata:
  name: dev-infra-management
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: |
    {"tlsClientConfig":{"insecure":false}}
  name: dev-management
  server: https://kubernetes.default.svc
