apiVersion: v1
kind: ConfigMap
metadata:
  name: cue-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cue
    spec:
      allowConcurrency: true
      generate:
        command: [sh, -xc]
        args: ["cue cmd dump ./..."]
      discover:
        fileName: "*.cue"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin
data:
  plugin.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: avp-kustomize
    spec:
      allowConcurrency: true
      lockRepo: false
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      discover:
        fileName: "kustomization.yaml"
