apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.0/manifests/install.yaml
  - resources/namespace.yaml
  - resources/clusters.yaml
  - resources/plugins.yaml
  - resources/bootstrap.yaml
  - resources/argocd-repositories.yaml
  - resources/argocd-repo-creds.yaml

  - ingress/argocd-backend-config.yaml
  - ingress/argocd-frontend-config.yaml
  - ingress/argocd-ingress.yaml
  - ingress/argocd-tls.yaml

patches:
  - path: patches/argocd-application-controller.yaml
  - path: patches/argocd-server-service.yaml
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argocd-notifications-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
  - path: patches/argocd-repo-server-deploy.yaml
  - path: patches/argocd-secret.yaml
  - path: patches/argocd-sa.yaml
