apiVersion: v1
kind: Secret
metadata:
  name: argocd-tls
type: kubernetes.io/tls
data:
  tls.crt: <path:projects/dev-infra/secrets/cf-tls-crt#eth-tls-crt | base64encode>
  tls.key: <path:projects/dev-infra/secrets/cf-tls-key#eth-tls-key | base64encode>
