name: "Update"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1" # https://crontab.guru/#0_10_*_*_1
jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/update-flake-lock@v21
        id: update
        with:
          nix-options: --accept-flake-config
          sign-commits: true
          pr-reviewers: selfuryon
          pr-assignees: selfuryon
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          pr-title: "chore: update flake.lock"
          commit-msg: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
      - name: Print PR number
        run: echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
